name: carapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.3
  flutter_lints: ^1.0.0
  google_nav_bar: ^5.0.5
  line_icons: ^2.0.0
  http: ^0.13.4
  cloud_firestore: ^3.1.7
  firebase_core: ^1.12.0
  image_picker: ^0.8.4+5
  fluttertoast: ^8.0.8
  firebase_storage: ^10.2.6
  firebase_database: ^9.0.6
  provider: ^6.0.2
  dio: ^4.0.4
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.1
  animated_splash_screen: ^1.1.0
  dropdown_button2: ^1.1.1
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.0.12
  flutter_localizations:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/car_icon.png
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
